.TH "pt100_table.h" 3 "Mit Jul 18 2012" "PT100 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pt100_table.h \- 
.PP
Tabelle mit PT100-Widerstandswerten von [-200 \&.\&.\&. +850]°C in 1K-Schritten\&.  

.SH SYNOPSIS
.br
.PP
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBR_MIN\fP   (unsigned long)(18493L)"
.br
.RI "\fIMinimaler Widerstandswert in mOhm\&. \fP"
.ti -1c
.RI "#define \fBR_MAX\fP   (unsigned long)(390263L)"
.br
.RI "\fIMaximaler Widerstandswert in mOhm\&. \fP"
.ti -1c
.RI "#define \fBT_MIN\fP   -200000L"
.br
.RI "\fIMinimale Temperatur der Widerstandstabelle in m°C\&. \fP"
.ti -1c
.RI "#define \fBT_MAX\fP   850000L"
.br
.RI "\fIMaximale Temperatur der Widerstandstabelle in m°C\&. \fP"
.ti -1c
.RI "#define \fBT_DIFF\fP   1000L"
.br
.RI "\fITemperaturintervall der Widerstandstabelle in mK\&. \fP"
.ti -1c
.RI "#define \fBINDEX_MAX\fP   1050"
.br
.RI "\fIMaximaler Index der PT100-Tabelle\&. \fP"
.ti -1c
.RI "#define \fBINDEX_ZERO\fP   200"
.br
.RI "\fIIndex für 0°C in der PT100-Tabelle\&. \fP"
.in -1c
.SS "Variablen"

.in +1c
.ti -1c
.RI "unsigned long const \fBpt100_table\fP []"
.br
.RI "\fITabelle mit PT100-Widerstandswerten von [-200 \&.\&.\&. +850]°C in 1K-Schritten\&. \fP"
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Tabelle mit PT100-Widerstandswerten von [-200 \&.\&.\&. +850]°C in 1K-Schritten\&. 

\fBAutor:\fP
.RS 4
Roman Buchert (roman.buchert@googlemail.com) 
.RE
.PP

.PP
Definiert in Datei \fBpt100_table\&.h\fP\&.
.SH "Makro-Dokumentation"
.PP 
.SS "#define \fBINDEX_MAX\fP   1050"
.PP
Maximaler Index der PT100-Tabelle\&. 
.PP
Definiert in Zeile 37 der Datei pt100_table\&.h\&.
.PP
Wird benutzt von pt100_R2T() und pt100_T2R()\&.
.SS "#define \fBINDEX_ZERO\fP   200"
.PP
Index für 0°C in der PT100-Tabelle\&. 
.PP
Definiert in Zeile 41 der Datei pt100_table\&.h\&.
.PP
Wird benutzt von pt100_R2T()\&.
.SS "#define \fBR_MAX\fP   (unsigned long)(390263L)"
.PP
Maximaler Widerstandswert in mOhm\&. 
.PP
Definiert in Zeile 21 der Datei pt100_table\&.h\&.
.PP
Wird benutzt von pt100_R2T()\&.
.SS "#define \fBR_MIN\fP   (unsigned long)(18493L)"
.PP
Minimaler Widerstandswert in mOhm\&. 
.PP
Definiert in Zeile 17 der Datei pt100_table\&.h\&.
.PP
Wird benutzt von pt100_R2T()\&.
.SS "#define \fBT_DIFF\fP   1000L"
.PP
Temperaturintervall der Widerstandstabelle in mK\&. 
.PP
Definiert in Zeile 33 der Datei pt100_table\&.h\&.
.PP
Wird benutzt von pt100_R2T() und pt100_T2R()\&.
.SS "#define \fBT_MAX\fP   850000L"
.PP
Maximale Temperatur der Widerstandstabelle in m°C\&. 
.PP
Definiert in Zeile 29 der Datei pt100_table\&.h\&.
.PP
Wird benutzt von pt100_T2R()\&.
.SS "#define \fBT_MIN\fP   -200000L"
.PP
Minimale Temperatur der Widerstandstabelle in m°C\&. 
.PP
Definiert in Zeile 25 der Datei pt100_table\&.h\&.
.PP
Wird benutzt von pt100_T2R()\&.
.SH "Variablen-Dokumentation"
.PP 
.SS "unsigned long const \fBpt100_table\fP[]"
.PP
Tabelle mit PT100-Widerstandswerten von [-200 \&.\&.\&. +850]°C in 1K-Schritten\&. Die Werte sind in mOhm angegeben 
.PP
Definiert in Zeile 51 der Datei pt100_table\&.h\&.
.PP
Wird benutzt von pt100_R2T() und pt100_T2R()\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für PT100 Library aus dem Quellcode\&.
